# frozen_string_literal: true

require "spec_helper"

RSpec.describe Code::Object::Integer do
  [
    ["10 % 5", "0"],
    ["5 * 2", "10"],
    ["2 ** 2", "4"],
    ["1 + 1", "2"],
    ["1 - 0", "1"],
    ["-1", "1 - 2"],
    ["1 / 2", "0.5"],
    ["1 < 2", "true"],
    ["1 <= 1", "true"],
    ["1 <=> 2", "-1"],
    ["1 > 0", "true"],
    ["1.greater(1)", "false"],
    ["1.greater(0)", "true"],
    ["1 >= 1", "true"],
    ["1.greater_or_equal(1)", "true"],
    ["1.greater_or_equal(2)", "false"],
    ["1 === 1", "true"],
    %w[-1.abs 1],
    %w[-1.ceil -1],
    %w[1234.ceil(-2) 1300],
    %w[-1.floor -1],
    %w[1234.floor(-2) 1200],
    %w[1.round 1],
    %w[1234.round(-2) 1200],
    %w[0.zero? true],
    %w[1.truncate 1],
    %w[1234.truncate(-2) 1200],
    %w[1.to_string :1],
    %w[1.to_integer 1],
    %w[1.to_decimal 1.0],
    %w[4.sqrt 2.0],
    %w[3.between?(1,5) true],
    %w[3.between?(4,5) false],
    %w[10.clamp(1,5) 5],
    %w[1.next 2],
    %w[1.successor 2],
    %w[1.previous 0],
    %w[1.predecessor 0],
    %w[5.divide(2) 2],
    ["5.divide_modulo(2)", "[2, 1]"],
    %w[5.remainder(2) 1],
    %w[Class(1.second) Duration],
    %w[Class(2.seconds) Duration],
    %w[Class(1.minute) Duration],
    %w[Class(2.minutes) Duration],
    %w[Class(1.hour) Duration],
    %w[Class(2.hours) Duration],
    %w[Class(1.day) Duration],
    %w[Class(2.days) Duration],
    %w[Class(1.week) Duration],
    %w[Class(2.weeks) Duration],
    %w[Class(1.month) Duration],
    %w[Class(2.months) Duration],
    %w[Class(1.year) Duration],
    %w[Class(2.years) Duration],
    ["1 + 2", "3"],
    ["2 - 1", "1"],
    ["a = 2 - 1 a", "1"]
  ].each do |input, expected|
    it "#{input} == #{expected}" do
      expect(Code.evaluate(input)).to eq(Code.evaluate(expected))
    end
  end
end
